devtools::use_data_raw()
install.packages("prenoms_0.1.0.tar.gz", repos = NULL, type = "source")
devtools::use_package("readxl")
devtools::use_package("ggplot2")
devtools::use_package("dplyr")
devtools::use_package("tidyr")
devtools::use_package("prenoms")
devtools::use_vignette("pack2")
devtools::build_vignettes()
